# Generated by Django 4.2.5 on 2023-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlApp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
