# Generated by Django 4.2.5 on 2023-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlApp', '0003_alter_comment_author_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Текст публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
